name: Preprocessing Automation

on:
  push:
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r preprocessing/requirements.txt

      - name: Run preprocessing script
        run: |
          python preprocessing/automate_Muhammad-Firdaus.py

      - name: Debug - Lihat isi direktori hasil
        run: |
          echo "Isi direktori preprocessing:"
          ls -R preprocessing/namadataset_preprocessing

      - name: Upload hasil preprocessing
        uses: actions/upload-artifact@v4
        with:
          name: wine_preprocessed
          path: preprocessing/namadataset_preprocessing/wine_preprocessed.csv
